# Exercise 3: Pandas Data Analysis and Manipulation

In [2]:
import numpy as np
import pandas as pd

## Series Examples

In [3]:
s = pd.Series([10, 20, 30])
s

0    10
1    20
2    30
dtype: int64

In [4]:
s_custom = pd.Series([100, 200, 300], index=['a','b','c'])
s_custom

a    100
b    200
c    300
dtype: int64

In [5]:
s_custom.values
s_custom.index

Index(['a', 'b', 'c'], dtype='str')

## DataFrame from List of Dict

In [6]:
data = [
    {'Name':'A','Age':20},
    {'Name':'B','Age':21},
    {'Name':'C','Age':22}
]
df = pd.DataFrame(data)
df

  Name  Age
0    A   20
1    B   21
2    C   22

## Iris Dataset

In [7]:
url = "https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv"
iris = pd.read_csv(url)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
iris.shape

(150, 5)

In [9]:
iris.rename(columns={
    'sepal_length':'Sepal_Length',
    'sepal_width':'Sepal_Width',
    'petal_length':'Petal_Length',
    'petal_width':'Petal_Width'
}, inplace=True)
iris.columns

Index(['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width',
       'species'],
      dtype='str')

In [10]:
iris['species'] = iris['species'].replace({
    'Iris-setosa':'setosa',
    'Iris-versicolor':'versicolor',
    'Iris-virginica':'virginica'
})

In [11]:
iris.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [12]:
iris['Petal_Size'] = np.where(iris['Petal_Length']>5,'Large','Small')
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width species Petal_Size
0           5.1          3.5           1.4          0.2  setosa      Small
1           4.9          3.0           1.4          0.2  setosa      Small
2           4.7          3.2           1.3          0.2  setosa      Small
3           4.6          3.1           1.5          0.2  setosa      Small
4           5.0          3.6           1.4          0.2  setosa      Small

In [13]:
iris.drop('Petal_Size', axis=1, inplace=True)

In [14]:
iris.iloc[0]

Sepal_Length       5.1
Sepal_Width        3.5
Petal_Length       1.4
Petal_Width        0.2
species         setosa
Name: 0, dtype: object

In [15]:
iris.iloc[50:55]

    Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor

In [16]:
iris[(iris['species']=='virginica') & (iris['Petal_Length']>6)]

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    species
105           7.6          3.0           6.6          2.1  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

In [17]:
iris.duplicated().sum()

np.int64(3)

In [18]:
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [19]:
iris.isnull().sum()

Sepal_Length    0
Sepal_Width     0
Petal_Length    0
Petal_Width     0
species         0
dtype: int64